### ISSUE TITLE
Possible LED 5v Logic solution

### ISSUE THREAD

**Issue by JellyTitan** [doesntfazer/Budgy#1]
In your readme it mentions your having issues with 3.3v logic and the LEDs. I'm working on this issue for my own split. YesterdayI found the Junco readme explicitly details a solve for this using a lower current draw mini-e variant, and a line shifter to bump the logic up from 3.3v to 5v.  

I haven't tested the layout myself, but if it's viable this might unblock you on V2. 

https://github.com/Daneski13/Junco#optional---rgb

**Comment by doesntfazer** [comment]
@JellyTitan I really appreciate you reaching out on this. I actually looked at level shifting as an option. If I remember correctly I was having issues finding in stock level shifters, which was why I was looking at an alternative method. It's been a couple of months since I worked on this, but I might just revisit this.
